### ISSUE TITLE
why so sexy 

### ISSUE THREAD

**Issue by mrfluffy-dev** [JanSolo1/EduCRM-API#1]
I cant take my eyes off the sexy code

**Comment by JanSolo1** [comment]
Here is my scientific response

( sqrt(pi * e^(2 * ln(x + 1) / cos^2(theta)) / integral from -∞ to ∞ of e^(-t^2) dt ) / 
  ( limit as n approaches ∞ of sum from k=1 to n of (1 - 1/k)^k ) * 
  ( gamma(1/2) * product from i=1 to 5 of log base 2 of (1 / x_i) ) / 
  ( sin(pi/3) + cos(theta/2) - tan(pi/4) )

**Solution:**
**NO U**
